# Generated by Django 5.1.2 on 2024-11-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equationsolution',
            name='solution',
        ),
        migrations.AddField(
            model_name='equationsolution',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
