# Generated by Django 5.1.2 on 2024-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_remove_equationsolution_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationsolution',
            name='root1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equationsolution',
            name='root2',
            field=models.FloatField(default=0.0),
        ),
    ]
